version: "3"
services:
  origin:
    # build: ./docker/origin
    image: docker.io/unifiedstreaming/vod2live:1.11.14
    ports:
      - 80:80
    environment: 
      - UspLicenseKey
    volumes:
      - ./smils:/var/www/unified-origin/smils
